nelmio_api_doc:
    documentation:
        info:
            title: Products API
            description: API to manage products
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            - ^/product(?!/doc$) # Accepts routes under /product except /product/doc
